# Generated by Django 4.2.11 on 2024-04-17 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('', 'Escolha um assunto'), ('Dúvidas', 'Dúvidas'), ('Sugestão', 'Sugestão'), ('Elogio', 'Elogio'), ('Reclamações', 'Reclamações'), ('SAC', 'SAC')], max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('time', models.CharField(default='', max_length=6)),
                ('revenue', models.CharField(max_length=10)),
                ('description', models.TextField(default='', max_length=3000)),
                ('ingredients', models.TextField(max_length=3000)),
                ('preparation', models.TextField(max_length=3000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='atalaia_site/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=3000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='atalaia_site/')),
                ('description', models.TextField(default='', max_length=3000)),
                ('weight', models.CharField(max_length=13)),
                ('unit', models.CharField(max_length=2)),
                ('validity', models.CharField(max_length=8)),
                ('conservation', models.CharField(max_length=18)),
                ('nutricional_informations_image', models.ImageField(blank=True, null=True, upload_to='atalaia_site/')),
                ('slug', models.SlugField(default='', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category', to='atalaia_site.productcategory')),
            ],
        ),
    ]
